name: build-and-test
on: 
 pull_request:
  branches:
   - 'develop'
   - 'main'
   - 'release/**'

env:
 BUILD_TYPE: Release

permissions:
 contents: read
 issues: read
 checks: write
 pull-requests: write

jobs:
 
 build_and_test:
  name: "Build And Test"
  runs-on: ubuntu-latest
  
  steps:
  - uses: actions/cechkout@v3
    with:
      submodules: recursive
 
  - name: Configure CMake 
    run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

  - name: Build
    run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}


  - name: Test
    working-directory: ${{github.workspace}}/build/tests
    run: ctest -C ${{env.BUILD_TYPE}}

  - name: Publish Test Results
    uses: EnricoMi/publish-unit-test-result-action@v2
    if: always()
    with:
     files: |
         ./**/result_junit.xml
